--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BreathTakinglyBinary/libDynamicForms
branches:
- master
- stable
projects:
  libDynamicForms:
    model: virion
    type: library
...
